### ISSUE TITLE
Argument of type 'string' is not assignable to parameter of type 'never'.

### ISSUE THREAD

**Issue by keesvanbemmel** [becem-gharbi/nuxt-directus#84]
My TS compiler gives error `Argument of type 'string' is not assignable to parameter of type 'never'.` when using your example code for readItems through rest. The error is shown at the collection name ("country" in this example.) Typescript complier is 5.4.5
```
import {
  readItems,
  useAsyncData,
  useDirectusRest,
} from "#imports";

const { data, refresh } = await useAsyncData(() =>
  useDirectusRest(readItems("country")),
);
```

**Comment by becem-gharbi** [comment]
This may be related to Directus SDK. I just pushed a release with its new major version. https://github.com/directus/directus/releases/tag/v10.11.0

**Comment by keesvanbemmel** [comment]
I upgraded, checked for SDK v16 and still have the same error.
![CleanShot 2024-05-08 at 17 26 53](https://github.com/becem-gharbi/nuxt-directus/assets/4633876/69fbea2b-d2dd-4cd1-ab41-8c6ce8f084ae)

![CleanShot 2024-05-08 at 17 27 05](https://github.com/becem-gharbi/nuxt-directus/assets/4633876/e29e0f5d-8164-4a57-b69a-9a30e733253c)

**Comment by becem-gharbi** [comment]
I've encountered this issue when the `DirectusSchema` global type is empty object. Can you confirm?

**Comment by keesvanbemmel** [comment]
Yes I had similar observations. Used your module from source and set the type of in useDirectusRest to any instead of DirectusSchema and then it worked fine.

**Comment by keesvanbemmel** [comment]
You say "when the global type is empty object" how does one set it to something else?

**Comment by becem-gharbi** [comment]
> You say "when the global type is empty object" how does one set it to something else?

https://github.com/becem-gharbi/nuxt-directus?tab=readme-ov-file#rest

**Comment by becem-gharbi** [comment]
This should be fixed now @2.4.1.

**Comment by keesvanbemmel** [comment]
It seems to be something else, not sure why. I globally declared DirectusSchema as you do in your playground. That didn't work, same error.

After this I upgraded to 2.4.1 of your package, still same error.

My root tsconfig.json looks like this:
```
{
  // https://nuxt.com/docs/guide/concepts/typescript
  "extends": "./.nuxt/tsconfig.json",
  "compilerOptions": {
    "paths": {
      "@/data/*": ["./data/*"],
      "@/types/*": ["./types/*"],
      "@/stores/*": ["./stores/*"],
      "#imports": ["./.nuxt/imports"]
    }
  }
}
```

If I append this to the file:
```
,
  "include": ["./types/index.d.ts"]
```

The never error goes away!

Not sure how to solve this, seems like VSCode doesn't really pick up the extended ./.nuxt/tsconfig stuff. Any thoughts?

**Comment by becem-gharbi** [comment]
Please provide a minimal reproducttion https://stackblitz.com/github/nuxt/starter/tree/v3.

Edit: Types are automatically included by Nuxt. Maybe the issue is related to vscode, that's why a reproduction would be helpfull.

**Comment by keesvanbemmel** [comment]
This repo reproduces the error. My VSCode shows the "never" error on line 17 in useCountryStore.ts

Deliberately added everything (also .nuxt and .output stuff) to be as complete as can be. node_modules is not added, npm i should take care of that.

https://github.com/keesvanbemmel/reproduce

![CleanShot 2024-05-10 at 10 57 39@2x](https://github.com/becem-gharbi/nuxt-directus/assets/4633876/6683bdf4-2ef8-43f0-a017-18177839306e)

**Comment by becem-gharbi** [comment]
In your reproduction `CustomDirectusTypes` is not imported correctly.

```diff
// index.d.ts
- import { CustomDirectusTypes } from ".";
+ import { CustomDirectusTypes } from "./types";
```

**Comment by keesvanbemmel** [comment]
Annoyingly, that indeed fixes the reproduction repo :)

~~That is, however, not the issue with my relevant repo :( would you mind taking a peek there?~~

I'll just use the reproduction repo and add stuff from my other, see when it breaks! Thanks for your insights!

**Comment by keesvanbemmel** [comment]
Just for future reference, I was using an old version of directus-typescript-gen, using latest fixed my issues
